version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo MY_EXPORTED_VAR = $MY_EXPORTED_VAR
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -R
artifacts:
  name: build#$CODEBUILD_BUILD_NUMBER
  files:
    - '*/my-file-3.txt'
  base-directory: artifacts/my-build-2
env:
  variables:
    MY_EXPORTED_VAR: "exported variable"
  exported-variables:
    - MY_EXPORTED_VAR