version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - */my-file-3.txt
    base-directory: my-build-2
